apiVersion: v1
kind: Service
metadata:
  name: mysql-sf
  namespace: name2
  labels:
    app: mysql
spec:
  selector:
    app: mysql-sf
  clusterIP: None
  ports:
    - name: http
      port: 3306
      protocol: TCP
