apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fruit-pvc
  namespace: name2
  labels:
    app: fruit-api
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi