apiVersion: v1
kind: Secret
metadata:
  name: fruit-secret
  namespace: name2
type: Opaque
data:
  DATABASE_HOST: bXlzcWwtc2Y=
  DATABASE_PORT: MzMwNg==
  DATABASE_NAME: ZGJfZnJ1aXQ=
  DATABASE_USERNAME: cm9vdA==