apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-sf
  namespace: name2
  labels:
    app: fruit-sf
spec:
  selector:
    matchLabels:
      app: fruit-sf
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fruit-sf
    spec:
      containers:
        - name: fruit-api
          image: k8smitocode1/java-fruit-api:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: fruit-secret
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: fruit-secret
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: fruit-secret
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fruit-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - name: http
              containerPort: 8090
          volumeMounts:
            - name: fruit-fs-storage
              mountPath: /var/www/html
      volumes:
        - name: fruit-fs-storage
          hostPath:
            path: /var/www/html
      restartPolicy: Always
