apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: name1
  labels:
    app: mysql
spec:
  volumes:
    - name: mysql-pvc-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
  containers:
    - name: mysql
      image: mysql
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
      ports:
        - containerPort: 3306
          name: http
      volumeMounts:
        - name: mysql-pvc-storage
          mountPath: /var/lib/mysql
  restartPolicy: Always
