apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fruit
  namespace: name1
  labels:
    app: fruit-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fruit
  template:
    metadata:
      labels:
        app: fruit
    spec:
      volumes:
        - name: fruit-pvc-storage
          persistentVolumeClaim:
            claimName: fruit-pvc
      containers:
        - name: fruit
          image: k8smitocode1/java-fruit-api:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: fruit-cm
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: fruit-cm
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: fruit-cm
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: fruit-cm
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8090
              name: http
          volumeMounts:
            - name: fruit-pvc-storage
              mountPath: /var/www/html
      restartPolicy: Always
